if (CMAKE_SYSTEM_NAME MATCHES "^(Linux|Android)$")
    set(TIO_PLATFORM_LINUX TRUE)
    if (CMAKE_SYSTEM_NAME STREQUAL "Android")
        set(TIO_PLATFORM_ANDROID TRUE)
    endif ()
    set(TIO_DEFAULT_BACKEND "epoll")
elseif (CMAKE_SYSTEM_NAME MATCHES "^(Darwin|iOS|tvOS|watchOS|visionOS)$")
    set(TIO_PLATFORM_APPLE TRUE)
    if (CMAKE_SYSTEM_NAME STREQUAL "Darwin")
        set(TIO_PLATFORM_MACOS TRUE)
    endif ()
    set(TIO_DEFAULT_BACKEND "kqueue")
elseif (CMAKE_SYSTEM_NAME STREQUAL "Windows")
    set(TIO_PLATFORM_WINDOWS TRUE)
    set(TIO_DEFAULT_BACKEND "iocp")
else ()
    message(FATAL_ERROR "Unsupported platform: ${CMAKE_SYSTEM_NAME}")
endif ()

set(TIO_BACKEND "${TIO_DEFAULT_BACKEND}" CACHE STRING "I/O backend (epoll, io_uring, kqueue, iocp)")
set_property(CACHE TIO_BACKEND PROPERTY STRINGS epoll io_uring kqueue iocp)

message(STATUS "tio platform: ${CMAKE_SYSTEM_NAME}")
message(STATUS "tio backend:  ${TIO_BACKEND}")

if (TIO_PLATFORM_LINUX)
    if (NOT TIO_BACKEND MATCHES "^(epoll|io_uring)$")
        unset(TIO_BACKEND CACHE)
        message(FATAL_ERROR "Linux only supports epoll or io_uring backend, got: ${TIO_BACKEND}")
    endif ()
endif ()

if (TIO_PLATFORM_APPLE)
    if (NOT TIO_BACKEND STREQUAL "kqueue")
        unset(TIO_BACKEND CACHE)
        message(FATAL_ERROR "Apple platforms only support the kqueue backend, got: ${TIO_BACKEND}")
    endif ()
endif ()
